import type { Holding } from './types';

export const holdings: Holding[] = [
  { name: "HDFC Bank", sector: "Financial Sector", exchange: "HDFCBANK", purchasePrice: 1490, qty: 50, yahoo: "HDFCBANK.NS", google: "HDFCBANK:NSE" },
  { name: "Bajaj Finance", sector: "Financial Sector", exchange: "BAJFINANCE", purchasePrice: 6466, qty: 15, yahoo: "BAJFINANCE.NS", google: "BAJFINANCE:NSE" },
  { name: "ICICI Bank", sector: "Financial Sector", exchange: "532174", purchasePrice: 780, qty: 84, yahoo: "ICICIBANK.NS", google: "ICICIBANK:NSE" },
  { name: "Bajaj Housing", sector: "Financial Sector", exchange: "544252", purchasePrice: 130, qty: 504, yahoo: "BAJAJHFL.NS", google: "BAJAJHFL:NSE" },
  { name: "Savani Financials", sector: "Financial Sector", exchange: "511577", purchasePrice: 24, qty: 1080, yahoo: "511577.BO", google: "511577:BOM" },
  { name: "Affle India", sector: "Tech Sector", exchange: "AFFLE", purchasePrice: 1151, qty: 50, yahoo: "AFFLE.NS", google: "AFFLE:NSE" },
  { name: "LTI Mindtree", sector: "Tech Sector", exchange: "LTIM", purchasePrice: 4775, qty: 16, yahoo: "LTIM.NS", google: "LTIM:NSE" },
  { name: "KPIT Tech", sector: "Tech Sector", exchange: "542651", purchasePrice: 672, qty: 61, yahoo: "KPITTECH.NS", google: "KPITTECH:NSE" },
  { name: "Tata Tech", sector: "Tech Sector", exchange: "544028", purchasePrice: 1072, qty: 63, yahoo: "TATATECH.NS", google: "TATATECH:NSE" },
  { name: "BLS E-Services", sector: "Tech Sector", exchange: "544107", purchasePrice: 232, qty: 191, yahoo: "BLSE.NS", google: "BLSE:NSE" },
  { name: "Tanla", sector: "Tech Sector", exchange: "532790", purchasePrice: 1134, qty: 45, yahoo: "TANLA.NS", google: "TANLA:NSE" },
  { name: "Dmart", sector: "Consumer", exchange: "DMART", purchasePrice: 3777, qty: 27, yahoo: "DMART.NS", google: "DMART:NSE" },
  { name: "Tata Consumer", sector: "Consumer", exchange: "532540", purchasePrice: 845, qty: 90, yahoo: "TATACONSUM.NS", google: "TATACONSUM:NSE" },
  { name: "Pidilite", sector: "Consumer", exchange: "500331", purchasePrice: 2376, qty: 36, yahoo: "PIDILITIND.NS", google: "PIDILITIND:NSE" },
  { name: "Tata Power", sector: "Power", exchange: "500400", purchasePrice: 224, qty: 225, yahoo: "TATAPOWER.NS", google: "TATAPOWER:NSE" },
  { name: "KPI Green", sector: "Power", exchange: "542323", purchasePrice: 875, qty: 50, yahoo: "KPIGREEN.NS", google: "KPIGREEN:NSE" },
  { name: "Suzlon", sector: "Power", exchange: "532667", purchasePrice: 44, qty: 450, yahoo: "SUZLON.NS", google: "SUZLON:NSE" },
  { name: "Gensol", sector: "Power", exchange: "542851", purchasePrice: 998, qty: 45, yahoo: "GENSOL.NS", google: "GENSOL:NSE" },
  { name: "Hariom Pipes", sector: "Pipe Sector", exchange: "543517", purchasePrice: 580, qty: 60, yahoo: "HARIOMPIPE.NS", google: "HARIOMPIPE:NSE" },
  { name: "Astral", sector: "Pipe Sector", exchange: "ASTRAL", purchasePrice: 1517, qty: 56, yahoo: "ASTRAL.NS", google: "ASTRAL:NSE" },
  { name: "Polycab", sector: "Pipe Sector", exchange: "542652", purchasePrice: 2818, qty: 28, yahoo: "POLYCAB.NS", google: "POLYCAB:NSE" },
  { name: "Clean Science", sector: "Others", exchange: "543318", purchasePrice: 1610, qty: 32, yahoo: "CLEAN.NS", google: "CLEAN:NSE" },
  { name: "Deepak Nitrite", sector: "Others", exchange: "506401", purchasePrice: 2248, qty: 27, yahoo: "DEEPAKNTR.NS", google: "DEEPAKNTR:NSE" },
  { name: "Fine Organic", sector: "Others", exchange: "541557", purchasePrice: 4284, qty: 16, yahoo: "FINEORG.NS", google: "FINEORG:NSE" },
  { name: "Gravita", sector: "Others", exchange: "533282", purchasePrice: 2037, qty: 8, yahoo: "GRAVITA.NS", google: "GRAVITA:NSE" },
  { name: "SBI Life", sector: "Others", exchange: "540719", purchasePrice: 1197, qty: 49, yahoo: "SBILIFE.NS", google: "SBILIFE:NSE" },
];
